apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - name: c1
    image: ubuntu
    command: ["/bin/bash","-c","sleep 10000"]
    volumeMounts:
    - name: emptydirvol
      mountPath: "/tmp/data1"
  - name: c2
    image: centos
    command: ["/bin/bash","-c","sleep 100000"]
    volumeMounts:
    - name: emptydirvol
      mountPath: "/tmp/data2"
  volumes:
  - name: emptydirvol
    emptyDir: {}