apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash","-c","sleep 100000"]
    volumeMounts:
    - name: hostpathvol
      mountPath: "/volume"
  volumes:
  - name: hostpathvol
    hostPath: 
      path: /tmp/hostpath