apiVersion: v1
kind: Pod
metadata:
  name: init-ex
  labels:
    app: html
spec:
  initContainers:
  - name: clone
    image: bitnami/git
    command:
    - git
    - clone
    - https://github.com/GirijalaAditya/web-server-template.git
    - /tmp
    volumeMounts:
    - name: vol
      mountPath: "/tmp"
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: vol
      mountPath: "/usr/share/nginx/html"
volumes:
- name: vol
  emptyDir: {}

# Service
--- 
apiVersion: v1
kind: Service
metadata:
  name: init-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: html