apiVersion: v1
kind: Pod
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  containers:
  - name: application
    image: curlimages/curl
    command: ['/bin/sh']
    args: ["-c","while true; do curl -s localhost:8080; sleep 2; done"]
  - name: nginx-proxy
    image: adityadevops/nginx-proxy
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: adityadevops/flask-proxy
    ports:
    - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask