apiVersion: v1
kind: ReplicationController
metadata:
  name: web-server-rc
  labels:
    app: web
spec:
  replicas: 2
  template:
    metadata:
      name: web-server
      labels:
        app: web
    spec:
      containers:
      - name: web-cotainer
        image: nginx:alpine
        ports:
        - containerPort: 80